services:
    oro_test.dumper.mysql:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Dumper\MysqlDumper'
        arguments:
            - '@symfony2_extension.kernel'
        tags:
            - { name: 'oro_test.db_dumper', driver: 'pdo_mysql' }

    oro_test.dumper.pgsql:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Dumper\PgsqlDumper'
        arguments:
            - '@symfony2_extension.kernel'
        tags:
            - { name: 'oro_test.db_dumper', driver: 'pdo_pgsql' }

    oro_test.dumper.file_cache:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Dumper\FileCacheDumper
        arguments:
            - '@symfony2_extension.kernel'
        tags:
            - { name: oro_test.dumper, priority: 20 }

    cli.controller.suite:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\SuiteController
        arguments:
            - '@suite.registry'
            - '%suite.configurations%'
            - '%oro_test.application_suites%'
        tags:
            - { name: cli.controller, priority: 1100 }

    mink.listener.sessions:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Listener\SessionsListener
        arguments:
            - '@mink'
            - '%mink.default_session%'
            - '%mink.javascript_session%'
            - '%mink.available_javascript_sessions%'
        tags:
            - { name: event_dispatcher.subscriber, priority: 0 }

    oro_test.listener.runtime_subscriber:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Listener\RunTimeSubscriber
        arguments:
            - '@mink'
            - '@symfony2_extension.kernel'
        tags:
            - { name: event_dispatcher.subscriber, priority: 10 }

    oro_test.listener.set_locale_subscriber:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Listener\SetLocaleSubscriber
        arguments:
            - '@oro_config.global'
        tags:
            - { name: event_dispatcher.subscriber, priority: 50 }

    oro_test.listener.feature_isolation_subscriber:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Listener\FeatureIsolationSubscriber
        arguments:
            - ~
            - '@oro_test.context.fixture_loader'
            - '@oro_element_factory'
            - '@oro_test.kernel_service_factory'
            - '@oro_test.reference_repository_initializer'
        tags:
            - { name: 'event_dispatcher.subscriber' }

    oro_test.listener.message_queue_consumer_process_subscriber:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Listener\MessageQueueConsumerProcessSubscriber'
        arguments:
            - '@symfony2_extension.kernel'
        tags:
            - { name: 'event_dispatcher.subscriber' }

    oro_test.listener.dump_environment_subscriber:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Listener\DumpEnvironmentSubscriber'
        arguments:
            - ~
            - '@oro_test.dumper.file_cache'
        tags:
            - { name: 'event_dispatcher.subscriber' }

    oro_test.listener.step_duration_measure_subscriber:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Listener\StepDurationMeasureSubscriber'
        arguments:
            - '@definition.finder'

    cli.controller.mesure_execution_time:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\MeasureExecutionTimeController
        arguments:
            - '@oro_test.listener.step_duration_measure_subscriber'
            - '@event_dispatcher'
        tags:
            - { name: 'cli.controller' }

    oro_element_factory:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Element\OroElementFactory'
        arguments:
            - '@mink'
            - '@mink.selectors_handler'
            - []

    oro_page_factory:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Element\OroPageFactory'
        arguments:
            - '@oro_element_factory'
            - []

    oro_behat_element_factory_initializer:
        class: 'Oro\Bundle\TestFrameworkBundle\Behat\Context\Initializer\ElementFactoryInitializer'
        arguments:
            - '@oro_element_factory'
            - '@oro_page_factory'
        tags:
            - { name: 'context.initializer' }

    oro_behat_fixture_loader_initializer:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Context\Initializer\FixtureLoaderInitializer
        arguments:
            - '@oro_test.context.fixture_loader'
        tags:
            - { name: 'context.initializer' }

    oro_test.context.fixture_loader:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\FixtureLoader
        arguments:
            - '@doctrine'
            - '@oro_test.entity_class_resolver'
            - '@oro_test.entity_supplement'
            - '@oro_test.alice_loader'

    oro_test.entity_class_resolver:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\EntityClassResolver
        arguments: ['@oro_entity.entity_alias_resolver']

    oro_test.entity_supplement:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\EntitySupplement
        arguments:
            - '@doctrine'
            - '@oro_test.reference_repository'
            - '@oro_security.owner.metadata_provider.chain'

    oro_test.reference_repository:
        class: Nelmio\Alice\Instances\Collection
        factory: ['@oro_test.alice_loader', getReferenceRepository]

    oro_test.reference_repository_initializer:
        class: '%oro_test.reference_initializer_class%'
        arguments:
            - '@doctrine'
            - '@oro_test.reference_repository'

    oro_test.alice_loader:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Fixtures\OroAliceLoader
        calls:
            - [setDoctrine, ['@doctrine']]

    oro_test.environment.handler.scenario_environment_handlre:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Environment\Handler\FeatureEnvironmentHandler
        arguments:
            - '@context.factory'
        tags:
            - { name: 'environment.handler', priority: 100 }
